<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251226184845 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE burger (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, prix DOUBLE PRECISION NOT NULL, image VARCHAR(255) DEFAULT NULL, archive BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etat VARCHAR(50) NOT NULL, type_commande VARCHAR(50) NOT NULL, montant_total DOUBLE PRECISION NOT NULL, client_id INT NOT NULL, zone_id INT DEFAULT NULL, livreur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D19EB6921 ON commande (client_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D9F2C3FAB ON commande (zone_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DF8646701 ON commande (livreur_id)');
        $this->addSql('CREATE TABLE complement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, prix DOUBLE PRECISION NOT NULL, image VARCHAR(255) DEFAULT NULL, archive BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ligne_commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, commande_id INT NOT NULL, burger_id INT DEFAULT NULL, menu_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3170B74B82EA2E54 ON ligne_commande (commande_id)');
        $this->addSql('CREATE INDEX IDX_3170B74B17CE5090 ON ligne_commande (burger_id)');
        $this->addSql('CREATE INDEX IDX_3170B74BCCD7E912 ON ligne_commande (menu_id)');
        $this->addSql('CREATE TABLE ligne_commande_complement (ligne_commande_id INT NOT NULL, complement_id INT NOT NULL, PRIMARY KEY (ligne_commande_id, complement_id))');
        $this->addSql('CREATE INDEX IDX_BB687091E10FEE63 ON ligne_commande_complement (ligne_commande_id)');
        $this->addSql('CREATE INDEX IDX_BB68709140D9D0AA ON ligne_commande_complement (complement_id)');
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, image VARCHAR(255) DEFAULT NULL, archive BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_burger (menu_id INT NOT NULL, burger_id INT NOT NULL, PRIMARY KEY (menu_id, burger_id))');
        $this->addSql('CREATE INDEX IDX_3CA402D5CCD7E912 ON menu_burger (menu_id)');
        $this->addSql('CREATE INDEX IDX_3CA402D517CE5090 ON menu_burger (burger_id)');
        $this->addSql('CREATE TABLE menu_complement (menu_id INT NOT NULL, complement_id INT NOT NULL, PRIMARY KEY (menu_id, complement_id))');
        $this->addSql('CREATE INDEX IDX_D909AAE6CCD7E912 ON menu_complement (menu_id)');
        $this->addSql('CREATE INDEX IDX_D909AAE640D9D0AA ON menu_complement (complement_id)');
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_paiement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant DOUBLE PRECISION NOT NULL, methode_paiement VARCHAR(50) NOT NULL, commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1DC7A1E82EA2E54 ON paiement (commande_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, telephone VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, prix_livraison DOUBLE PRECISION NOT NULL, quartiers TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DF8646701 FOREIGN KEY (livreur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74B17CE5090 FOREIGN KEY (burger_id) REFERENCES burger (id)');
        $this->addSql('ALTER TABLE ligne_commande ADD CONSTRAINT FK_3170B74BCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id)');
        $this->addSql('ALTER TABLE ligne_commande_complement ADD CONSTRAINT FK_BB687091E10FEE63 FOREIGN KEY (ligne_commande_id) REFERENCES ligne_commande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_commande_complement ADD CONSTRAINT FK_BB68709140D9D0AA FOREIGN KEY (complement_id) REFERENCES complement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_burger ADD CONSTRAINT FK_3CA402D5CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_burger ADD CONSTRAINT FK_3CA402D517CE5090 FOREIGN KEY (burger_id) REFERENCES burger (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_complement ADD CONSTRAINT FK_D909AAE6CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_complement ADD CONSTRAINT FK_D909AAE640D9D0AA FOREIGN KEY (complement_id) REFERENCES complement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "CommandeItems" DROP CONSTRAINT "FK_CommandeItems_Menus_MenuId"');
        $this->addSql('ALTER TABLE "CommandeItems" DROP CONSTRAINT "FK_CommandeItems_Burgers_BurgerId"');
        $this->addSql('ALTER TABLE "CommandeItems" DROP CONSTRAINT "FK_CommandeItems_Commandes_CommandeId"');
        $this->addSql('ALTER TABLE "CommandeItems" DROP CONSTRAINT "FK_CommandeItems_Complements_ComplementId"');
        $this->addSql('ALTER TABLE "Commandes" DROP CONSTRAINT "FK_Commandes_Clients_ClientId"');
        $this->addSql('ALTER TABLE "Commandes" DROP CONSTRAINT "FK_Commandes_Livreurs_LivreurId"');
        $this->addSql('ALTER TABLE "Commandes" DROP CONSTRAINT "FK_Commandes_Zones_ZoneId"');
        $this->addSql('ALTER TABLE "MenuComplements" DROP CONSTRAINT "FK_MenuComplements_Complements_ComplementId"');
        $this->addSql('ALTER TABLE "MenuComplements" DROP CONSTRAINT "FK_MenuComplements_Menus_MenuId"');
        $this->addSql('ALTER TABLE "Menus" DROP CONSTRAINT "FK_Menus_Burgers_BurgerId"');
        $this->addSql('ALTER TABLE "Paiements" DROP CONSTRAINT "FK_Paiements_Commandes_CommandeId"');
        $this->addSql('DROP TABLE "Burgers"');
        $this->addSql('DROP TABLE "Clients"');
        $this->addSql('DROP TABLE "CommandeItems"');
        $this->addSql('DROP TABLE "Commandes"');
        $this->addSql('DROP TABLE "Complements"');
        $this->addSql('DROP TABLE "Livreurs"');
        $this->addSql('DROP TABLE "MenuComplements"');
        $this->addSql('DROP TABLE "Menus"');
        $this->addSql('DROP TABLE "Paiements"');
        $this->addSql('DROP TABLE "Zones"');
        $this->addSql('DROP TABLE "__EFMigrationsHistory"');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "Burgers" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "Description" VARCHAR(500) DEFAULT NULL, "Prix" NUMERIC(10, 2) NOT NULL, "ImageUrl" TEXT DEFAULT NULL, "EstArchive" BOOLEAN NOT NULL, "EstBestSeller" BOOLEAN NOT NULL, "DateCreation" TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE TABLE "Clients" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "Prenom" VARCHAR(100) NOT NULL, "Telephone" VARCHAR(20) NOT NULL, "Email" VARCHAR(100) NOT NULL, "MotDePasse" TEXT NOT NULL, "Adresse" VARCHAR(200) DEFAULT NULL, "PhotoUrl" TEXT DEFAULT NULL, "DateInscription" TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE TABLE "CommandeItems" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "CommandeId" INT NOT NULL, "BurgerId" INT DEFAULT NULL, "MenuId" INT DEFAULT NULL, "ComplementId" INT DEFAULT NULL, "Quantite" INT NOT NULL, "PrixUnitaire" NUMERIC(10, 2) NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE INDEX "IX_CommandeItems_MenuId" ON "CommandeItems" ("MenuId")');
        $this->addSql('CREATE INDEX "IX_CommandeItems_CommandeId" ON "CommandeItems" ("CommandeId")');
        $this->addSql('CREATE INDEX "IX_CommandeItems_BurgerId" ON "CommandeItems" ("BurgerId")');
        $this->addSql('CREATE INDEX "IX_CommandeItems_ComplementId" ON "CommandeItems" ("ComplementId")');
        $this->addSql('CREATE TABLE "Commandes" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "NumeroCommande" TEXT NOT NULL, "ClientId" INT NOT NULL, "TypeService" INT NOT NULL, "Etat" INT NOT NULL, "ZoneId" INT DEFAULT NULL, "LivreurId" INT DEFAULT NULL, "DateCommande" TIMESTAMP(0) WITH TIME ZONE NOT NULL, "DateLivraison" TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE INDEX "IX_Commandes_ZoneId" ON "Commandes" ("ZoneId")');
        $this->addSql('CREATE INDEX "IX_Commandes_ClientId" ON "Commandes" ("ClientId")');
        $this->addSql('CREATE INDEX "IX_Commandes_LivreurId" ON "Commandes" ("LivreurId")');
        $this->addSql('CREATE TABLE "Complements" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "Prix" NUMERIC(10, 2) NOT NULL, "ImageUrl" TEXT DEFAULT NULL, "Type" INT NOT NULL, "EstArchive" BOOLEAN NOT NULL, "DateCreation" TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE TABLE "Livreurs" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "Prenom" VARCHAR(100) NOT NULL, "Telephone" VARCHAR(20) NOT NULL, "Email" TEXT NOT NULL, "MotDePasse" TEXT NOT NULL, "EstActif" BOOLEAN NOT NULL, "DateInscription" TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE TABLE "MenuComplements" ("MenuId" INT NOT NULL, "ComplementId" INT NOT NULL, PRIMARY KEY ("MenuId", "ComplementId"))');
        $this->addSql('CREATE INDEX "IX_MenuComplements_ComplementId" ON "MenuComplements" ("ComplementId")');
        $this->addSql('CREATE INDEX IDX_76FD6A4372CDF098 ON "MenuComplements" ("MenuId")');
        $this->addSql('CREATE TABLE "Menus" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "ImageUrl" TEXT DEFAULT NULL, "EstArchive" BOOLEAN NOT NULL, "DateCreation" TIMESTAMP(0) WITH TIME ZONE NOT NULL, "BurgerId" INT NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE INDEX "IX_Menus_BurgerId" ON "Menus" ("BurgerId")');
        $this->addSql('CREATE TABLE "Paiements" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "CommandeId" INT NOT NULL, "Montant" NUMERIC(10, 2) NOT NULL, "ModePaiement" INT NOT NULL, "DatePaiement" TIMESTAMP(0) WITH TIME ZONE NOT NULL, "Reference" VARCHAR(100) DEFAULT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE UNIQUE INDEX "IX_Paiements_CommandeId" ON "Paiements" ("CommandeId")');
        $this->addSql('CREATE TABLE "Zones" ("Id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nom" VARCHAR(100) NOT NULL, "PrixLivraison" NUMERIC(10, 2) NOT NULL, "Quartiers" VARCHAR(500) DEFAULT NULL, "DateCreation" TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY ("Id"))');
        $this->addSql('CREATE TABLE "__EFMigrationsHistory" ("MigrationId" VARCHAR(150) NOT NULL, "ProductVersion" VARCHAR(32) NOT NULL, PRIMARY KEY ("MigrationId"))');
        $this->addSql('ALTER TABLE "CommandeItems" ADD CONSTRAINT "FK_CommandeItems_Menus_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Menus" ("Id") NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "CommandeItems" ADD CONSTRAINT "FK_CommandeItems_Burgers_BurgerId" FOREIGN KEY ("BurgerId") REFERENCES "Burgers" ("Id") NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "CommandeItems" ADD CONSTRAINT "FK_CommandeItems_Commandes_CommandeId" FOREIGN KEY ("CommandeId") REFERENCES "Commandes" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "CommandeItems" ADD CONSTRAINT "FK_CommandeItems_Complements_ComplementId" FOREIGN KEY ("ComplementId") REFERENCES "Complements" ("Id") NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "Commandes" ADD CONSTRAINT "FK_Commandes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "Commandes" ADD CONSTRAINT "FK_Commandes_Livreurs_LivreurId" FOREIGN KEY ("LivreurId") REFERENCES "Livreurs" ("Id") NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "Commandes" ADD CONSTRAINT "FK_Commandes_Zones_ZoneId" FOREIGN KEY ("ZoneId") REFERENCES "Zones" ("Id") NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "MenuComplements" ADD CONSTRAINT "FK_MenuComplements_Complements_ComplementId" FOREIGN KEY ("ComplementId") REFERENCES "Complements" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "MenuComplements" ADD CONSTRAINT "FK_MenuComplements_Menus_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Menus" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "Menus" ADD CONSTRAINT "FK_Menus_Burgers_BurgerId" FOREIGN KEY ("BurgerId") REFERENCES "Burgers" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "Paiements" ADD CONSTRAINT "FK_Paiements_Commandes_CommandeId" FOREIGN KEY ("CommandeId") REFERENCES "Commandes" ("Id") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D19EB6921');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D9F2C3FAB');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DF8646701');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B82EA2E54');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74B17CE5090');
        $this->addSql('ALTER TABLE ligne_commande DROP CONSTRAINT FK_3170B74BCCD7E912');
        $this->addSql('ALTER TABLE ligne_commande_complement DROP CONSTRAINT FK_BB687091E10FEE63');
        $this->addSql('ALTER TABLE ligne_commande_complement DROP CONSTRAINT FK_BB68709140D9D0AA');
        $this->addSql('ALTER TABLE menu_burger DROP CONSTRAINT FK_3CA402D5CCD7E912');
        $this->addSql('ALTER TABLE menu_burger DROP CONSTRAINT FK_3CA402D517CE5090');
        $this->addSql('ALTER TABLE menu_complement DROP CONSTRAINT FK_D909AAE6CCD7E912');
        $this->addSql('ALTER TABLE menu_complement DROP CONSTRAINT FK_D909AAE640D9D0AA');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E82EA2E54');
        $this->addSql('DROP TABLE burger');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE complement');
        $this->addSql('DROP TABLE ligne_commande');
        $this->addSql('DROP TABLE ligne_commande_complement');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_burger');
        $this->addSql('DROP TABLE menu_complement');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE zone');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
